Imports

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
 

Data Preprocessing

In [15]:
with open('Salary_Data.csv') as r:
    my_csv = pd.read_csv(r)

x = my_csv.iloc[:, :-1].values
y = my_csv.iloc[:, -1:].values


dividing to train and test datasets

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=0)

fitting(train) the model

In [17]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

Predicting

In [18]:
x_test

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [19]:
y_pred=regressor.predict(x_test)

In [20]:
y_pred

array([[ 40748.96184072],
       [122699.62295594],
       [ 64961.65717022],
       [ 63099.14214487],
       [115249.56285456],
       [107799.50275317]])

In [21]:
y2_pred=regressor.predict(x_train)

In [22]:
y2_pred

array([[116180.82036723],
       [ 64030.39965754],
       [ 76136.74732229],
       [100349.44265179],
       [ 53786.56701814],
       [ 74274.23229695],
       [ 56580.33955616],
       [ 68686.68722091],
       [103143.21518981],
       [ 90105.61001239],
       [ 38886.44681538],
       [124562.13798128],
       [ 54717.82453082],
       [ 47267.76442943],
       [ 81724.29239833],
       [ 82655.549911  ],
       [ 61236.62711953],
       [ 56580.33955616],
       [110593.27529119],
       [ 45405.24940409],
       [ 37023.93179003],
       [ 92899.38255041],
       [ 72411.7172716 ],
       [ 64030.39965754]])

In [23]:
x_train

array([[ 9.6],
       [ 4. ],
       [ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])